services:
  - type: web
    name: shop-with-sahil-api
    runtime: docker
    rootDir: backend

    dockerfilePath: ./Dockerfile

    envVars:
      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: MAIL_HOST
        sync: false

      - key: MAIL_PORT
        sync: false

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false