services:
  - type: web
    name: shop-with-sahil-api
    runtime: java
    rootDir: backend

    buildCommand: mvn clean package -DskipTests

    startCommand: java -jar target/online-shopping-cart-1.0.0.jar

    envVars:
      - key: DB_URL
        sync: false

      - key: DB_USERNAME
        sync: false

      - key: DB_PASSWORD
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: MAIL_HOST
        sync: false

      - key: MAIL_PORT
        sync: false

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false